symfony/src/Entity/Wallet.php
<?php

namespace App\Entity;

use App\Repository\WalletRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=WalletRepository::class)
 */
class Wallet
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="float", scale=6)
     */
    private $amount;

    /**
     * @ORM\Column(type="float", scale=6)
     */
    private $initial_value;

    /**
     * @ORM\Column(type="date")
     */
    private $creation_date;

    /**
     * @ORM\Column(type="float", scale=6)
     */
    private $current_value;

    /**
     * @ORM\Column(type="boolean")
     */
    private $status;

    /**
     * @ORM\ManyToOne(targetEntity=Curency::class, inversedBy="wallets")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Currency;

    /**
     * @ORM\Column(type="float", scale=6)
     */
    private $initialAmount;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getInitialValue(): ?float
    {
        return $this->initial_value;
    }

    public function setInitialValue(float $initial_value): self
    {
        $this->initial_value = $initial_value;

        return $this;
    }

    public function getCreationDate(): ?\DateTimeInterface
    {
        return $this->creation_date;
    }

    public function setCreationDate(\DateTimeInterface $creation_date): self
    {
        $this->creation_date = $creation_date;

        return $this;
    }

    public function getCurrentValue(): ?float
    {
        return $this->current_value;
    }

    public function setCurrentValue(float $current_value): self
    {
        $this->current_value = $current_value;

        return $this;
    }

    public function getStatus(): ?bool
    {
        return $this->status;
    }

    public function setStatus(bool $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getCurrency(): ?Curency
    {
        return $this->Currency;
    }

    public function setCurrency(?Curency $Currency): self
    {
        $this->Currency = $Currency;

        return $this;
    }

    public function getInitialAmount(): ?float
    {
        return $this->initialAmount;
    }

    public function setInitialAmount(float $initialAmount): self
    {
        $this->initialAmount = $initialAmount;

        return $this;
    }
}

symfony/src/Controller/DefaultController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\WalletRepository;
use Symfony\Contracts\HttpClient\HttpClientInterface;
use Doctrine\Persistence\ManagerRegistry;


class DefaultController extends AbstractController
{
    /**
     * @Route("/", name="app_default")
     */
    public function index(ManagerRegistry $doctrine, WalletRepository $walletRepository, HttpClientInterface $client): Response
    {
        $entityManager = $doctrine->getManager();

        /*--------------------------------------------- get all data transactions*/
        
        $data = $walletRepository->findByStatusWallet([true]);
        
        foreach ($data as $trade){

           
            /*---------------------------------------------Check current Value*/

            $amount = $trade->getAmount();
            $slug = $trade->getCurrency()->getSlug();
            $url= 'https://pro-api.coinmarketcap.com/v2/tools/price-conversion?symbol='.$slug.'&amount='.$amount.'&convert=EUR';
    
            /*call to api */
            
            $response = $client->request('GET', $url, [
                'headers' => [
                    'Accept' => 'application/json',
                    'X-CMC_PRO_API_KEY' => '073c15a6-fd76-40d2-8efd-9a62ecab8077'
                ],
            ]);
            $content = $response->getContent(); 
            $trade->setCurrentValue(json_decode($content)->data[0]->quote->EUR->price);   
    
            $entityManager->flush($trade);
        }

        /*--------------------------------------------- call of the template*/
        return $this->render('default/index.html.twig', [
            'controller_name' => 'Crypto Tracker',
            'data_wallet'=> $data
        ]);
    }
}

symfony/templates/default/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ controller_name }}{% endblock %}

{% block stylesheets %}
        <style>{{source('@css/index.css')}}</style>
{% endblock %}

{% block nav %}
    <ul class="flex">
        {% if data_wallet is empty %}
                {% else %}
                <li>
                    <a id="link-edit" href="/delete?id={{ data_wallet[0].id }}">
                        <img src="{{ asset('/img/picto/edit.png') }}" />
                    </a>
                </li>
        {% endif %}    
        <li>
            <a href="/add">
                <img src="{{ asset('/img/picto/+.png') }}" />
            </a>
        </li>
    </ul>
{% endblock %}

{% block body %}
    
    <header class="flex x-center y-center">
        <div id="particles-js"></div>

        {% if data_wallet is empty %}
            <input id='value-viewer' value='0' />
            {% else %}
                {% if  ((data_wallet[0].currentValue / data_wallet[0].amount - data_wallet[0].InitialValue / data_wallet[0].Initialamount) *data_wallet[0].amount) >= 0 %}
                    <input id='value-viewer' value='+ {{ ((data_wallet[0].currentValue / data_wallet[0].amount - data_wallet[0].InitialValue / data_wallet[0].Initialamount) *data_wallet[0].amount)|round(2, 'floor') }}' />
                {% else %}
                    <input id='value-viewer' value='- {{ ((data_wallet[0].currentValue / data_wallet[0].amount - data_wallet[0].InitialValue / data_wallet[0].Initialamount) *data_wallet[0].amount)|round(2, 'floor') }}' />
                {% endif %}
        {% endif %}
       
    </header>
    <div class="container">
        
        {% if data_wallet is empty %}
            <h2> Pas d'actifs pour le moment</h2>
            {% else %}
                <ul id="transaction-list">
            
                    {% for exanges in data_wallet %}
                        <li class="flex y-center" onClick=changeViewTransaction(event)>
                            <form class="flex x-space-b y-center">        
                                <input type="hidden" value="{{ ((exanges.currentValue / exanges.amount - exanges.InitialValue / exanges.Initialamount) * exanges.amount)|round(2, 'floor') }}" readonly/>
                                <input type="hidden" value="{{ exanges.amount }}" readonly/>
                                <input type="hidden" value="{{ exanges.id }}" readonly/>
                                <div class="flex y-center">
                                    <img src ="uploads/{{ exanges.Currency.Images.Name }}" />
                                    <p>{{ exanges.Currency.Slug }} ({{ exanges.Currency.Name }})</p>
                                </div>
                                <a href='/chart?id={{ exanges.id }}'>
                                    {% if  ((exanges.currentValue / exanges.amount - exanges.InitialValue / exanges.InitialValue)|round(2, 'floor')) > 100 %}
                                            <img src="{{ asset('/img/picto/arrow-up.png') }}" />
                                            <img src="{{ asset('/img/picto/arrow-up.png') }}" />
                                        {% elseif  ((exanges.currentValue / exanges.amount - exanges.InitialValue / exanges.InitialValue)|round(2, 'floor')) > 0 %}
                                            <img src="{{ asset('/img/picto/arrow-up.png') }}" />
                                        {% else %}
                                            <img src="{{ asset('/img/picto/arrow-down.png') }}" />
                                    {% endif %}
                                </a>
                            </form>
                        </li>
                    {% endfor %}
                </ul>                
        {% endif %}
    
        
    </div>
    <script src="http://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"></script>
    <script src="http://threejs.org/examples/js/libs/stats.min.js"></script>
    <script>

        /*header get value*/
        document.querySelector('#transaction-list li:first-child').classList.add('transaction-viewed');
        
        let changeViewTransaction = (event)=>{
            document.querySelector('.transaction-viewed').classList.remove('transaction-viewed');
            event.currentTarget.classList.add('transaction-viewed');

            let sign = ''

            if(event.currentTarget.children[0].children[0].value>=0){
                sign = '+ ';
            }else{
                 sign = '- ';
            }
            document.getElementById('value-viewer').value = sign + event.currentTarget.children[0].children[0].value;
            document.getElementById('link-edit').setAttribute("href", "/delete?id=" + event.currentTarget.children[0].children[2].value);
        }

        /*haeder animation*/
        particlesJS("particles-js", {
            "particles": {
                "number": {
                "value": 80,
                "density": {
                    "enable": true,
                    "value_area": 25
                }
                },
                "color": {
                "value": ["#751E59",'#C2820C', "#A8140C"]
                },
                "shape": {
                "type": "circle",
                "stroke": {
                    "width": 0,
                    "color": "#000000"
                },
                "polygon": {
                    "nb_sides": 5
                },
                "image": {
                    "src": "img/github.svg",
                    "width": 100,
                    "height": 100
                }
                },
                "opacity": {
                "value": 1,
                "random": false,
                "anim": {
                    "enable": false,
                    "speed": 1,
                    "opacity_min": 0.1,
                    "sync": false
                }
                },
                "size": {
                "value": 4,
                "random": true,
                "anim": {
                    "enable": false,
                    "speed": 40,
                    "size_min": 0.1,
                    "sync": false
                }
                },
                "line_linked": {
                "enable": false,
                "distance": 150,
                "color": "#ffffff",
                "opacity": 0.4,
                "width": 1
                },
                "move": {
                "enable": true,
                "speed": 2,
                "direction": "bottom",
                "random": true,
                "straight": false,
                "out_mode": "out",
                "bounce": false,
                "attract": {
                    "enable": false,
                    "rotateX": 600,
                    "rotateY": 1200
                }
                }
            },
            "interactivity": {
                "detect_on": "canvas",
                "events": {
                "onhover": {
                    "enable": false,
                    "mode": "repulse"
                },
                "onclick": {
                    "enable": false,
                    "mode": "push"
                },
                "resize": true
                },
                "modes": {
                "grab": {
                    "distance": 400,
                    "line_linked": {
                    "opacity": 1
                    }
                },
                "bubble": {
                    "distance": 400,
                    "size": 40,
                    "duration": 2,
                    "opacity": 8,
                    "speed": 3
                },
                "repulse": {
                    "distance": 200,
                    "duration": 0.4
                },
                "push": {
                    "particles_nb": 4
                },
                "remove": {
                    "particles_nb": 2
                }
            }},"retina_detect": true
        });var count_particles, stats, update; stats = new Stats; stats.setMode(0); stats.domElement.style.position = 'absolute'; stats.domElement.style.left = '0px'; stats.domElement.style.top = '0px'; update = function() { stats.begin(); stats.end(); if (window.pJSDom[0].pJS.particles && window.pJSDom[0].pJS.particles.array) { count_particles.innerText = window.pJSDom[0].pJS.particles.array.length; } requestAnimationFrame(update); }; requestAnimationFrame(update);;
    </script>
     

{% endblock %}